import jsPDF from 'jspdf';

export interface InvoiceData {
  invoiceNumber: string;
  studentId: string;
  studentName: string;
  program: string;
  academicYear: string;
  semester: string;
  items: { description: string; amount: number }[];
  totalAmount: number;
  amountPaid: number;
  balance: number;
  dueDate: string;
  issueDate: string;
}

export interface ReceiptData {
  receiptNumber: string;
  studentId: string;
  studentName: string;
  program: string;
  paymentDate: string;
  paymentMethod: string;
  amount: number;
  description: string;
  balance: number;
}

export interface AdmissionLetterData {
  studentName: string;
  studentId: string;
  program: string;
  programCode: string;
  degreeLevel: string;
  admissionDate: string;
  academicYear: string;
  semester: string;
  campus: string;
}

export interface StudentIDData {
  studentId: string;
  studentName: string;
  program: string;
  programCode: string;
  year: number;
  photo?: string;
  issueDate: string;
  expiryDate: string;
}

export class PDFGenerator {
  private static addHeader(doc: jsPDF, title: string) {
    // UNRE Logo and Header
    doc.setFontSize(20);
    doc.setFont('helvetica', 'bold');
    doc.text('UNIVERSITY OF NATURAL RESOURCES', 105, 20, { align: 'center' });
    doc.text('AND ENVIRONMENT', 105, 28, { align: 'center' });

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text('P.O. Box 6101, Boroko, NCD, Papua New Guinea', 105, 35, { align: 'center' });
    doc.text('Tel: +675 325 9099 | Email: info@unre.ac.pg | www.unre.ac.pg', 105, 40, { align: 'center' });

    // Title
    doc.setDrawColor(0, 128, 96);
    doc.setLineWidth(0.5);
    doc.line(20, 45, 190, 45);

    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(0, 128, 96);
    doc.text(title, 105, 55, { align: 'center' });

    doc.setDrawColor(0, 128, 96);
    doc.line(20, 60, 190, 60);

    doc.setTextColor(0, 0, 0);
  }

  private static addFooter(doc: jsPDF) {
    const pageHeight = doc.internal.pageSize.height;
    doc.setFontSize(8);
    doc.setFont('helvetica', 'italic');
    doc.setTextColor(100, 100, 100);
    doc.text('This is an official document generated by UNRE Student Registration System', 105, pageHeight - 15, { align: 'center' });
    doc.text(`Generated on: ${new Date().toLocaleString()}`, 105, pageHeight - 10, { align: 'center' });
  }

  static generateInvoice(data: InvoiceData): jsPDF {
    const doc = new jsPDF();

    this.addHeader(doc, 'STUDENT FEE INVOICE');

    let y = 75;

    // Invoice Details
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.text(`Invoice Number: ${data.invoiceNumber}`, 20, y);
    doc.text(`Issue Date: ${data.issueDate}`, 140, y);
    y += 7;
    doc.text(`Student ID: ${data.studentId}`, 20, y);
    doc.text(`Due Date: ${data.dueDate}`, 140, y);
    y += 7;

    doc.setFont('helvetica', 'normal');
    doc.text(`Student Name: ${data.studentName}`, 20, y);
    y += 5;
    doc.text(`Program: ${data.program}`, 20, y);
    y += 5;
    doc.text(`Academic Year: ${data.academicYear}`, 20, y);
    doc.text(`Semester: ${data.semester}`, 100, y);

    y += 15;

    // Table Header
    doc.setFillColor(0, 128, 96);
    doc.setTextColor(255, 255, 255);
    doc.rect(20, y, 170, 8, 'F');
    doc.setFont('helvetica', 'bold');
    doc.text('Description', 25, y + 5);
    doc.text('Amount (K)', 160, y + 5, { align: 'right' });

    y += 8;
    doc.setTextColor(0, 0, 0);
    doc.setFont('helvetica', 'normal');

    // Items
    data.items.forEach((item) => {
      doc.text(item.description, 25, y + 5);
      doc.text(item.amount.toFixed(2), 160, y + 5, { align: 'right' });
      doc.line(20, y + 7, 190, y + 7);
      y += 7;
    });

    y += 5;

    // Totals
    doc.setFont('helvetica', 'bold');
    doc.text('Total Amount:', 120, y);
    doc.text(`K ${data.totalAmount.toFixed(2)}`, 160, y, { align: 'right' });
    y += 7;

    doc.setTextColor(0, 128, 0);
    doc.text('Amount Paid:', 120, y);
    doc.text(`K ${data.amountPaid.toFixed(2)}`, 160, y, { align: 'right' });
    y += 7;

    doc.setTextColor(200, 0, 0);
    doc.text('Balance Due:', 120, y);
    doc.text(`K ${data.balance.toFixed(2)}`, 160, y, { align: 'right' });

    doc.setTextColor(0, 0, 0);

    this.addFooter(doc);

    return doc;
  }

  static generateReceipt(data: ReceiptData): jsPDF {
    const doc = new jsPDF();

    this.addHeader(doc, 'PAYMENT RECEIPT');

    let y = 75;

    // Receipt Details
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text(`Receipt Number: ${data.receiptNumber}`, 20, y);
    y += 10;

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(`Student ID: ${data.studentId}`, 20, y);
    doc.text(`Date: ${data.paymentDate}`, 140, y);
    y += 7;
    doc.text(`Student Name: ${data.studentName}`, 20, y);
    y += 7;
    doc.text(`Program: ${data.program}`, 20, y);
    y += 15;

    // Payment Details Box
    doc.setFillColor(240, 240, 240);
    doc.rect(20, y, 170, 40, 'F');
    doc.setDrawColor(0, 128, 96);
    doc.rect(20, y, 170, 40);

    y += 10;
    doc.setFont('helvetica', 'bold');
    doc.text('Payment Details', 25, y);
    y += 10;

    doc.setFont('helvetica', 'normal');
    doc.text(`Description: ${data.description}`, 25, y);
    y += 7;
    doc.text(`Payment Method: ${data.paymentMethod}`, 25, y);
    y += 7;

    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(0, 128, 0);
    doc.text(`Amount Paid: K ${data.amount.toFixed(2)}`, 25, y);

    y += 15;
    doc.setFontSize(10);
    doc.setTextColor(0, 0, 0);
    doc.setFont('helvetica', 'normal');
    doc.text(`Remaining Balance: K ${data.balance.toFixed(2)}`, 25, y);

    y += 20;

    // Thank you note
    doc.setFontSize(10);
    doc.setFont('helvetica', 'italic');
    doc.text('Thank you for your payment!', 105, y, { align: 'center' });
    y += 7;
    doc.text('Please keep this receipt for your records.', 105, y, { align: 'center' });

    this.addFooter(doc);

    return doc;
  }

  static generateAdmissionLetter(data: AdmissionLetterData): jsPDF {
    const doc = new jsPDF();

    this.addHeader(doc, 'OFFER OF ADMISSION');

    let y = 75;

    // Date and Reference
    doc.setFontSize(10);
    doc.text(`Date: ${data.admissionDate}`, 140, y);
    y += 7;
    doc.text(`Ref: UNRE/ADM/${data.studentId}`, 140, y);
    y += 15;

    // Addressee
    doc.setFont('helvetica', 'bold');
    doc.text(data.studentName, 20, y);
    y += 10;

    // Body
    doc.setFont('helvetica', 'normal');
    doc.text('Dear Applicant,', 20, y);
    y += 10;

    doc.setFont('helvetica', 'bold');
    doc.text('RE: OFFER OF ADMISSION', 20, y);
    y += 10;

    doc.setFont('helvetica', 'normal');
    const bodyText = [
      `We are pleased to offer you admission to the ${data.program} (${data.programCode})`,
      `at the University of Natural Resources and Environment for the ${data.academicYear} academic year,`,
      `commencing in ${data.semester}.`,
      '',
      'This offer is subject to the following conditions:',
      '',
      '1. Payment of all required fees by the specified deadline',
      '2. Submission of original academic certificates for verification',
      '3. Completion of the enrollment process',
      '4. Compliance with university rules and regulations',
      '',
      `Your Student ID is: ${data.studentId}`,
      `Campus: ${data.campus}`,
      '',
      'To accept this offer, please:',
      '',
      '1. Log into the student portal using your Student ID',
      '2. Complete the online enrollment form',
      '3. Pay the required fees',
      '4. Upload any required documents',
      '',
      'We look forward to welcoming you to UNRE!',
    ];

    bodyText.forEach((line) => {
      if (y > 250) {
        doc.addPage();
        y = 20;
      }
      doc.text(line, 20, y);
      y += 5;
    });

    y += 10;

    // Signature
    doc.setFont('helvetica', 'bold');
    doc.text('Dr. John Kamuso', 20, y);
    y += 5;
    doc.setFont('helvetica', 'normal');
    doc.text('Director of Admissions', 20, y);
    y += 5;
    doc.text('University of Natural Resources and Environment', 20, y);

    this.addFooter(doc);

    return doc;
  }

  static generateStudentID(data: StudentIDData): jsPDF {
    const doc = new jsPDF({
      orientation: 'landscape',
      unit: 'mm',
      format: [85.6, 53.98] // Credit card size
    });

    // Background
    doc.setFillColor(0, 128, 96);
    doc.rect(0, 0, 85.6, 53.98, 'F');

    // White content area
    doc.setFillColor(255, 255, 255);
    doc.roundedRect(3, 3, 79.6, 47.98, 2, 2, 'F');

    // Header
    doc.setTextColor(0, 128, 96);
    doc.setFontSize(8);
    doc.setFont('helvetica', 'bold');
    doc.text('UNIVERSITY OF NATURAL RESOURCES', 42.8, 8, { align: 'center' });
    doc.text('AND ENVIRONMENT', 42.8, 12, { align: 'center' });
    doc.setFontSize(6);
    doc.text('STUDENT IDENTIFICATION CARD', 42.8, 16, { align: 'center' });

    // Photo placeholder
    doc.setDrawColor(0, 128, 96);
    doc.setLineWidth(0.5);
    doc.rect(6, 20, 18, 22);
    if (!data.photo) {
      doc.setFontSize(6);
      doc.text('PHOTO', 15, 31, { align: 'center' });
    }

    // Student Details
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(7);
    doc.setFont('helvetica', 'bold');
    doc.text(`ID: ${data.studentId}`, 27, 22);

    doc.setFontSize(8);
    doc.text(data.studentName.toUpperCase(), 27, 27);

    doc.setFontSize(6);
    doc.setFont('helvetica', 'normal');
    doc.text(`${data.program}`, 27, 31, { maxWidth: 52 });
    doc.text(`Program: ${data.programCode}`, 27, 35);
    doc.text(`Year: ${data.year}`, 27, 39);

    // Footer
    doc.setFontSize(5);
    doc.setTextColor(100, 100, 100);
    doc.text(`Issued: ${data.issueDate}`, 6, 47);
    doc.text(`Expires: ${data.expiryDate}`, 60, 47);

    return doc;
  }

  static downloadPDF(doc: jsPDF, filename: string) {
    doc.save(filename);
  }

  static getPDFBlob(doc: jsPDF): Blob {
    return doc.output('blob');
  }

  static getPDFBase64(doc: jsPDF): string {
    return doc.output('datauristring');
  }
}
